### ISSUE TITLE
copy/copySync meta issue

### ISSUE THREAD

**Issue by RyanZim** [jprichardson/node-fs-extra#509]
@manidlou I think you mentioned `copySync` still needs updated to match the changes you made to `copy` in `develop`. Is that correct? What else needs done before releasing the work done on `develop`?

Just FYI, I'm planning on releasing a major version with just the changes in `copy`/`copySync`; that way if there's regressions, we can simply tell people not to upgrade until we get things fixed.

---

**Edit: Tasklist:**

- [ ] `copySync` needs updated to match `copy`
  - [x] Remove `recursive` option
  - [x] Fix #83
  - [x] Fix #198
  - [x] Fix #464
- [x] Port #511 to `develop`

**Comment by RyanZim** [comment]
Posting here, just a reminder to myself that I want to add async `filter` function support sometime, not sure if I'll get it done in this release.

**Comment by manidlou** [comment]
That's correct @RyanZim. In terms of changes for `copySync`, these are the things that I think need to be changed or fixed:

- There is a `recursive` option that was never been documented, which I think needs to be removed as it directly affects the `copySync` behavior for symlinks ([src](https://github.com/jprichardson/node-fs-extra/blob/develop/lib/copy-sync/copy-sync.js#L56)). Related issue: #447.
-  `copySync` currently fails for the old and infamous issues of #83 and #198.
- I also like to test if we get a better perf by using `recursive` pattern instead of `Array.forEach` when copying directories.

I do my best to complete them as fast as possible!

> I'm planning on releasing a major version with just the changes in copy/copySync; that way if there's regressions, we can simply tell people not to upgrade until we get things fixed.

Sounds good! :+1:

**Comment by RyanZim** [comment]
Also noting https://github.com/jprichardson/node-fs-extra/pull/511 needs ported.

I'm starting a tasklist in the OP; @manidlou please check off items that are merged to `develop`.

**Comment by RyanZim** [comment]
Anything else that needs done here @manidlou?

**Comment by manidlou** [comment]
> Anything else that needs done here @manidlou?

I think we are done here!
